# 显示在加密文本前的标识
flag = "低语:"
# 混淆原始数据的密钥, 尽量不要低于32位
key = "XDXDtudou@KeyFansClub^_^Encode!!"
# 生成加密hash的派生密钥
derive_key = "BORBER"
# 映射 0-255 u8 数值为中文字符的字典, 需要是排序后的, 排序算法为 rust 自身的 sort() , 目前未提供额外字典检验及排序工具, 但有后续计划
dict = [
    '七', '万', '三', '下', '东', '中', '乡', '乾', '于', '五', '亦', '亲', '亿', '他', '令', '以',
    '伊', '休', '众', '住', '依', '便', '信', '修', '倒', '僧', '兄', '先', '六', '写', '凉', '刚',
    '创', '利', '功', '劫', '勒', '北', '千', '卢', '印', '即', '去', '参', '及', '友', '双', '号',
    '各', '名', '吼', '告', '呼', '和', '哈', '善', '困', '在', '多', '夜', '夫', '央', '夷', '奉',
    '如', '妇', '妖', '妙', '姪', '孕', '孙', '孝', '孤', '宇', '守', '安', '宗', '定', '宝', '实',
    '室', '害', '寂', '寡', '尊', '尸', '尼', '尽', '山', '师', '帝', '幽', '广', '庙', '度', '开',
    '弟', '弥', '德', '心', '忧', '念', '怖', '怜', '急', '恐', '恤', '息', '惊', '惜', '想', '慈',
    '戏', '戒', '护', '拔', '持', '捐', '捨', '排', '提', '放', '故', '教', '敬', '数', '文', '方',
    '施', '族', '时', '昼', '普', '智', '曰', '曳', '月', '朋', '未', '术', '杀', '来', '树', '栗',
    '根', '桥', '梦', '梭', '楞', '槃', '此', '死', '殊', '殿', '毒', '毘', '求', '沙', '济', '涅',
    '消', '清', '游', '灭', '灯', '焰', '爱', '牟', '特', '王', '琉', '瑟', '璃', '生', '界', '百',
    '皂', '真', '睦', '矜', '知', '碍', '礼', '祖', '福', '秘', '积', '稳', '穆', '究', '空', '竟',
    '粟', '精', '纷', '经', '罗', '老', '者', '耨', '胜', '能', '至', '舍', '艺', '花', '苏', '茶',
    '药', '萨', '蒙', '藐', '虚', '行', '西', '解', '诃', '说', '诵', '诸', '谛', '谨', '豆', '贤',
    '贫', '资', '足', '路', '输', '过', '进', '远', '迦', '通', '逝', '造', '遮', '醯', '释', '重',
    '量', '金', '閦', '闍', '阴', '阿', '陀', '除', '陵', '隶', '难', '须', '颠', '首', '高', '麽']
# 优化部分常见格式
key_words = [
    ["magnet:?xt=urn:btih:", "▚m"],
    ["https://www.aliyundrive.com/s/", "▚a0"],
    ["点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。", "▚a1"],
    ["https://pan.baidu.com/s/", "▚b0"],
    ["复制这段内容后打开百度网盘手机App，操作更方便哦", "▚b1"],
    ["提取码:", "▚b2"]
]
# 推荐为 0, 经测试, 0 时效果好且快, 而且并非越大压缩越短, 实测中间等级有更短于22级的现象
# 且 0 时数量级在 微秒, 10-20 数量级在毫秒甚至百毫秒
zstd_level = 0
