[workspace]
members = [
    "whisperer",
    "whisperer-cli",
    "whisperer-server",
    "whisperer-svelte-ts/src-tauri",
    "whisperer-serverless-vercel/api"
]

[profile.release]
opt-level = 's'
lto = true
